version: '3'

services:
  mongo_db:
    container_name: mongo_trakto
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: trakto
      MONGO_INITDB_ROOT_PASSWORD: trakto_pass
    ports:
      - "27017:27017"
